# Generated by Django 4.0.4 on 2022-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
